FROM maven:latest AS deps

WORKDIR /app

RUN apt update && apt install -y --no-install-recommends entr && rm -rf /var/lib/apt/lists/*

COPY pom.xml /bom/pom.xml
RUN mvn -f /bom/pom.xml install -N

COPY services/feed-service/.mvn .mvn
COPY services/feed-service/mvnw services/feed-service/pom.xml ./
RUN ./mvnw -T 4 dependency:go-offline

COPY services/feed-service/src ./src

CMD ["sh", "-lc", "find src pom.xml | entr -rn ./mvnw spring-boot:run"]
