spring:
  application:
    name: post-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/picshare-realm
          jwk-set-uri: http://keycloak:8080/realms/picshare-realm/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      additional-paths: src/main/resources
    livereload: 
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080

eureka:
  client.service_url.defaultZone: http://discovery-server:8761/eureka
  instance:
    secure-port-enabled: false
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

info:
  app:
    name: ${spring.application.name}
    version: 0.0.1
    environment: dev

management:
  endpoints:
    web:
      exposure:
        include: 
        - health
        - info
        - metrics

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: DEBUG
