services:

  keycloak:
    build:
      context: ./services/keycloak/
    env_file: ./env/keycloak.env
    command:
      start-dev
    ports:
      - "8090:8080"
      - "8443:8443"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - picshare_network

  keycloak-db:
    image: postgres:latest
    env_file: ./env/keycloak.env
    volumes:
      - keycloak-service-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_network


  user-service:
    image: user-service:latest
    build:
      context: ./services/user-service/
    env_file: ./env/user.env
    depends_on:
      user-db:
        condition: service_healthy
    networks:
        - picshare_network

  user-db:
    image: postgres:latest
    env_file: ./env/user.env
    volumes: 
    - user-service-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_network

volumes:
  keycloak-service-data:
  user-service-data:

networks:
  picshare_network:
    driver: bridge
