services:

  angular:
    container_name: angular-dev
    build:
      context: ./picshare-frontend/
      dockerfile: Dockerfile.dev
    ports:
    - "4200:4200"
    networks:
    - frontend
    develop:
      watch:
      - action: sync
        path: ./picshare-frontend/src
        target: /app/src

  gateway:
    container_name: gateway-dev
    build:
      context: .
      dockerfile: gateway/Dockerfile.dev
    env_file: ./env/gateway.env
    depends_on:
    - keycloak
    - discovery-server
    ports:
    - "8080:8080"
    - "5005:5005"
    - "35729:35729"
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    develop:
      watch:
      - action: sync
        path: ./gateway/src
        target: /app/src
      - action: sync
        path: ./gateway/pom.xml
        target: /app/pom.xml
    networks: 
    - picshare_internal
    - frontend

  discovery-server:
    build: 
      context: .
      dockerfile: services/discovery-server/Dockerfile.dev
    ports:
    - "5010:5005"
    - "35735:35729"
    - "8761:8761"
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    develop:
      watch:
      - action: sync
        path: ./services/discovery-server/src
        target: /app/src
      - action: sync
        path: ./services/discovery-server/pom.xml
        target: /app/pom.xml
    networks: 
    - user-network
    - picshare_internal

  keycloak:
    build:
      context: ./services/keycloak/
    env_file: ./env/keycloak.env
    command: start-dev
    ports:
    - "8090:8080"
    - "8443:8443"
    depends_on:
      user-service:
        condition: service_started
      keycloak-db:
        condition: service_healthy
    networks:
    - picshare_internal
    - keycloak-network
    - frontend

  keycloak-db:
    image: postgres:latest
    env_file: ./env/keycloak.env
    volumes:
    - keycloak-service-data:/var/lib/postgresql
    expose:
    - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - keycloak-network

  user-service:
    container_name: user-dev
    build:
      context: .
      dockerfile: services/user-service/Dockerfile.dev
    env_file: ./env/user.env
    depends_on:
    - user-db
    - discovery-server
    ports:
    - "5006:5005"
    - "35730:35729"
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    develop:
      watch:
      - action: sync
        path: ./services/user-service/src
        target: /app/src
      - action: sync
        path: ./services/user-service/pom.xml
        target: /app/pom.xml
    networks: 
    - user-network
    - picshare_internal

  user-db:
    image: postgres:latest
    env_file: ./env/user.env
    volumes: 
    - user-service-data:/var/lib/postgresql
    expose:
    - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - user-network

  feed-service:
    container_name: feed-dev
    build:
      context: .
      dockerfile: services/feed-service/Dockerfile.dev
    env_file: ./env/feed.env
    depends_on:
    - discovery-server
    - feed-db
    ports:
    - "5007:5005"
    - "35731:35729"
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    develop:
      watch:
      - action: sync
        path: ./services/feed-service/src
        target: /app/src
      - action: sync
        path: ./services/feed-service/pom.xml
        target: /app/pom.xml
    networks: 
    - feed-network
    - picshare_internal

  feed-db:
    image: postgres:latest
    env_file: ./env/feed.env
    volumes: 
    - feed-service-data:/var/lib/postgresql
    expose:
    - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - feed-network

  post-service:
    container_name: post-dev
    build:
      context: .
      dockerfile: services/post-service/Dockerfile.dev
    env_file: ./env/post.env
    depends_on:
    - discovery-server
    - post-db
    ports:
    - "5008:5005"
    - "35733:35729"
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    develop:
      watch:
      - action: sync
        path: ./services/post-service/src
        target: /app/src
      - action: sync
        path: ./services/post-service/pom.xml
        target: /app/pom.xml
    networks: 
    - post-network
    - picshare_internal

  post-db:
    image: postgres:latest
    env_file: ./env/post.env
    volumes: 
    - post-service-data:/var/lib/postgresql
    expose:
    - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - post-network

  storage-service:
    container_name: storage-dev
    build:
      context: .
      dockerfile: services/storage-service/Dockerfile.dev
    depends_on:
    - discovery-server
    - minio
    ports:
    - "5009:5005"
    - "35734:35729"
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    develop:
      watch:
      - action: sync
        path: ./services/storage-service/src
        target: /app/src
      - action: sync
        path: ./services/storage-service/pom.xml
        target: /app/pom.xml
    networks: 
    - storage-network
    - picshare_internal

  minio:
    image: minio/minio
    container_name: minio
    ports:
    - "9001:9001"
    - "9000:9000"
    expose:
    - "9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
    - storage-network
    volumes:
    - minio-data:/data

volumes:
  keycloak-service-data:
  user-service-data:
  post-service-data:
  feed-service-data:
  minio-data:

networks:
  user-network:
  post-network:
  keycloak-network:
  feed-network:
  storage-network:
  picshare_internal:
  frontend:
