services:

  frontend:
    build:
      context: ./picshare-frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    networks:
      - frontend
    develop:
      watch:
        - action: sync
          path: ./picshare-frontend/
          target: /app

  keycloak:
    build:
      context: ./services/keycloak/
    env_file: ./env/keycloak.env
    command:
      start-dev
    ports:
      - "8090:8080"
      - "8443:8443"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - picshare_internal
      - frontend

  keycloak-db:
    image: postgres:latest
    env_file: ./env/keycloak.env
    volumes:
      - keycloak-service-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_internal

  user-service:
    image: user-service:latest
    build:
      context: ./services/user-service/
    env_file: ./env/user.env
    depends_on:
      user-db:
        condition: service_healthy
    networks:
        - picshare_internal

  user-db:
    image: postgres:latest
    env_file: ./env/user.env
    volumes: 
    - user-service-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - picshare_internal

volumes:
  keycloak-service-data:
  user-service-data:

networks:
  picshare_internal:
    driver: bridge
  frontend:
    driver: bridge
