FROM maven:latest AS deps

WORKDIR /app

RUN apt update && apt install -y --no-install-recommends entr && rm -rf /var/lib/apt/lists/*

COPY .mvn .mvn
COPY mvnw pom.xml ./
RUN ./mvnw -T 4 dependency:go-offline

COPY src ./src

CMD ["sh", "-lc", "find src pom.xml | entr -r ./mvnw spring-boot:run"]
