spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  instance.hostname: localhost
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url.defaultzone: http://${eureka.instance.hostname}:${server.port}/eureka

management:
  endpoints:
    web:
      exposure:
        include: 
        - health
        - info
  
  endpoint:
    health:
      show-details: always

  tracing:
    sampling.probability: 1
    enabled: true
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO
