ui-uri: http://angular:4200
gateway-uri: http://localhost:8080
discovery-server-uri: http://discovery-server:8761


spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
          default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:


          # Redirection from / to /ui/
          - id: home
            uri: ${gateway-uri}
            predicates:
            - Path=/
            filters:
            - RedirectTo=301,${gateway-uri}/ui/

          - id: ui-silent-sso
            uri: ${ui-uri}
            predicates:
            - Path=/ui/silent-check-sso.html
            filters:
            - AddResponseHeader=X-Frame-Options,SAMEORIGIN
          
          # Serve a SPA through the gateway (requires it to have a baseHref set as /ui)
          - id: ui-regular
            uri: ${ui-uri}
            predicates:
            - Path=/ui/**
                
          - id: user-service
            uri: lb://user-service
            predicates:
            - Path=/api/user/**
            filters:
            - StripPrefix=1

          - id: feed-service
            uri: lb://feed-service
            predicates:
            - Path=/api/feed/**
            filters:
            - StripPrefix=1

          - id: post-service
            uri: lb://post-service
            predicates:
            - Path=/api/post/**
            filters:
            - StripPrefix=1

          - id: storage-service
            uri: lb://storage-service
            predicates:
            - Path=/media/**
            - Method=GET

  application:
    name: gateway

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      additional-paths: src/main/resources
    livereload: 
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/picshare-realm
          jwk-set-uri: http://keycloak:8080/realms/picshare-realm/protocol/openid-connect/certs
          
server:
  port: 8080

eureka:
  client.service_url.defaultZone: http://discovery-server:8761/eureka
  instance:
    secure-port-enabled: false
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

info:
  app:
    name: ${spring.application.name}
    version: 0.0.1
    environment: dev

management:
  endpoints:
    web:
      exposure:
        include: 
        - health
        - info
        - metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling.probability: 1
    enabled: true
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans


logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    org.springframework.boot.autoconfigure.web: INFO
    reactor.netty: INFO
    redisrateLimiter: INFO
