logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

spring:
  application:
    name: Gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/
          jwk-set-uri: http://localhost:8090/realms/picshare-realm/protocol/openid-connect/certs

gateway:
  services:
    post-service:
      uri: http://post-service:8080/
      fallback: placeholder
      path: /api/post/**
    user-service:
      uri: http://user-service:8080/
      fallback: placeholder
      path: /api/user/**
    feed-service:
      uri: http://feed-service:8080/
      fallback: placeholder
      path: /api/feed/*
