gateway-uri: http://localhost:8080
user-service-uri: http://user-service:8080
feed-service-uri: http://feed-service:8080


spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
          - id: user-service
            uri: ${user-service-uri}
            predicates:
            - Path=/api/user/**
            filters:
            - StripPrefix=1

          - id: feed-service
            uri: ${feed-service-uri}
            predicates:
            - Path=/api/feed/**
            filters:
            - StripPrefix=1

          - id: post-service
            uri: ${post-service-uri}
            predicates:
            - Path=/api/post/**
            filters:
            - StripPrefix=1

  application:
    name: Gateway

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      additional-paths: src/main/resources
    livereload: 
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/
          issuer-uri: "http://localhost:8090/realms/picshare-realm"
          
server:
  port: 8080

logging:
  level:
    reactor.netty.http.server: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.cloud.gateway.route.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
