spring:
  application:
    name: Feed Service

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload: 
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
